### ISSUE TITLE
Fallback to reading the entire file when filehandle.createReadStream() isn't available

### ISSUE THREAD

**Issue by cuongvo** [oblador/esbuild-server#4]
[filehandle.createReadStream](https://nodejs.org/api/fs.html#filehandlecreatereadstreamoptions) has only been available since NodeJS v16.11.0. Users not yet on a version this recent will be prevented from using this package due to us not gracefully falling back to another implementation.

See: https://github.com/oblador/esbuild-server/blob/c26201077fbcb6800ae8dc82229dd8470a5d782a/src/index.ts#L188-L189

**Comment by cuongvo** [comment]
We're on 14.x, and it's not a trivial upgrade due to our scale. I think supporting non-EOL releases makes sense (14.x, 16.x, 18.x, 19.x) when backwards compatibility is relatively straight forward (as is in this case -- if `createReadStream` doesn't exist on the `FileHandle`, use `fs.createReadStream`).

**Comment by oblador** [comment]
Sure, that would be great!

**Comment by oblador** [comment]
@cuongvo Still up for that PR?

**Comment by oblador** [comment]
Closing due to lack of response
